### ISSUE TITLE
run build error:Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`

### ISSUE THREAD

**Issue by webYouth** [lance-yi/vue-cli3-multipage#5]
#具体错误
# ERROR  TypeError: Cannot read property '__expression' of undefined
TypeError: Cannot read property '__expression' of undefined
    at Object.toConfig (/Users/mima123/ht_testVersion/ht_project/node_modules/webpack-chain/src/Plugin.js:55:38)
    at clean.Object.assign.plugins.plugins.values.map.plugin (/Users/mima123/ht_testVersion/ht_project/node_modules/webpack-chain/src/Config.js:129:61)
    at Array.map (<anonymous>)
    at module.exports.toConfig (/Users/mima123/ht_testVersion/ht_project/node_modules/webpack-chain/src/Config.js:129:40)
    at Service.resolveWebpackConfig (/Users/mima123/ht_testVersion/ht_project/node_modules/@vue/cli-service/lib/Service.js:218:34)
    at PluginAPI.resolveWebpackConfig (/Users/mima123/ht_testVersion/ht_project/node_modules/@vue/cli-service/lib/PluginAPI.js:115:25)
    at module.exports (/Users/mima123/ht_testVersion/ht_project/node_modules/@vue/cli-service/lib/commands/build/resolveAppConfig.js:34:25)
    at build (/Users/mima123/ht_testVersion/ht_project/node_modules/@vue/cli-service/lib/commands/build/index.js:124:50)
    at api.registerCommand (/Users/mima123/ht_testVersion/ht_project/node_modules/@vue/cli-service/lib/commands/build/index.js:72:13)
    at Service.run (/Users/mima123/ht_testVersion/ht_project/node_modules/@vue/cli-service/lib/Service.js:203:12)
    at Object.<anonymous> (/Users/mima123/ht_testVersion/ht_project/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-cli-multipage@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-cli-multipage@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mima123/.npm/_logs/2019-03-21T10_55_05_330Z-debug.log

#配置文件
#/**
 * 方案
 * 生成的文件为
 * -dist
 * 	- css
 * 		- index.xxx.css
 * 		- page1.xxx.css
 * 		- page2.xxx.css
 * 	- img
 *  - index.html
 * 	- page1.html
 * 	- page2.html
 */
let path = require('path')
let glob = require('glob')
//配置pages多页面获取当前文件夹下的html和js
function getEntry(globPath) {
	let entries = {},
		basename, tmp, pathname;

	glob.sync(globPath).forEach(function(entry) {
		basename = path.basename(entry, path.extname(entry));
		// console.log(entry)
		tmp = entry.split('/').splice(-3);
		pathname = basename; // 正确输出js和html的路径

		// console.log(pathname)
		entries[pathname] = {
			entry: 'src/' + tmp[0] + '/' + tmp[1] + '/main.js',
			template: 'src/' + tmp[0] + '/' + tmp[1] + '/' + tmp[2],
			title:  tmp[2],
			filename: tmp[2]
		};
	});
	return entries;
}

let pages = getEntry('./src/pages/**?/*.html');
//配置end
module.exports = {
  lintOnSave: false, //禁用eslint
	productionSourceMap: false,
	pages,
	devServer: {
		index: 'index.html', //默认启动serve 打开index页面
		open: process.platform === 'darwin',
		host: '',
		port: 8080,
		https: false,
		hotOnly: false,
		proxy: null, // 设置代理
		before: app => {}
  },
  // css相关配置
  css: {
    extract: false, // 是否使用css分离插件 ExtractTextPlugin
    sourceMap: false, // 开启 CSS source maps?
    loaderOptions: {
      less: {
        javascriptEnabled: true
      }
    }, // css预设器配置项
    modules: false // 启用 CSS modules for all css / pre-processor files.
  },
  // 是否为 Babel 或 TypeScript 使用 thread-loader。该选项在系统的 CPU 有多于一个内核时自动启用，仅作用于生产构建。
  parallel: require('os').cpus().length > 1,
  
	chainWebpack: config => {
		config.module
			.rule('images')
			.use('url-loader')
			.loader('url-loader')
			.tap(options => {
				// 修改它的选项...
				options.limit = 100
				return options
			})
		Object.keys(pages).forEach(entryName => {
			config.plugins.delete(`prefetch-${entryName}`);
		});
		if(process.env.NODE_ENV === "production") {
			config.plugin("extract-css").tap(() => [{
				path: path.join(__dirname, "./dist"),
				filename: "css/[name].[contenthash:8].css"
			}]);
		}
	},
	configureWebpack: config => {
		if(process.env.NODE_ENV === "production") {
			config.output = {
        path: path.join(__dirname, "./dist"),
        publicPath: "/",        
				filename: "js/[name].[contenthash:8].js"			
			};
		}
	}
}

**Comment by webYouth** [comment]
找了好久不知道具体哪里出问题了，希望解决，不解决提个思路也好，多谢

**Comment by webYouth** [comment]
打包错误已解决，本地运行的时候extract: true,设置成false引起，但还是出现大量的Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`，是否是版本太低引起，希望提示，多谢多谢

**Comment by M69W** [comment]
> 打包错误已解决，本地运行的时候extract: true,设置成false引起，但还是出现大量的Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`，是否是版本太低引起，希望提示，多谢多谢



`npm update caniuse-lite browserslist`没有作用，
我的方法是卸载后，再安装，
运行`npm run build` 就没有提示`Browserslist: caniuse-lite is outdated. Please run next command npm update caniuse-lite browserslist`
```
npm uninstall caniuse-lite browserslist
npm install caniuse-lite browserslist
```
